--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Zonasky/Timber
build-by-default: true
branches:
- main
projects:
  Timber:
    icon: meta/icon.png
    path: ""
    libs:
        - src: VennDev/LibVapmPMMP/LibVapmPMMP
          version: ^1.6
          branch: "main"
...
