name: Timber
version: 2.6.0
api: 5.0.0
main: Zonasky\Timber\Main
author: ["Inaayat", "skyss0fly"]
description: Instantly chops down trees with Timber
website: https://github.com/Zonasky/Timber
